### PR TITLE
Fix alpha bugs

### LINKED ISSUE #121: Data file still uses addressbook.json instead of tutorcentral.json
The application still saves data to 'addressbook.json' file. This should be updated to 'tutorcentral.json' or similar to reflect the rebranded application name.

### LINKED ISSUE #122: JAR file still named addressbook.jar
The built JAR file is still named 'addressbook.jar' instead of 'tutorcentral.jar'. This should be updated for consistency with the rebranded application.

### LINKED ISSUE #123: Config file references should be updated from AddressBook to Tutor Central
Configuration files and preferences still reference 'AddressBook' in their internal structure. These should be updated to 'Tutor Central' for consistency.

### LINKED ISSUE #124: Incomplete test coverage in JsonUtilTest
JsonUtilTest.java contains two TODO comments for missing tests: jsonUtil_readJsonStringToObjectInstance_correctObject() and jsonUtil_writeThenReadObjectToJson_correctObject(). These tests should be implemented to ensure proper JSON serialization/deserialization coverage.

### LINKED ISSUE #125: Missing error handling for file operations
The application should have better error handling for file I/O operations, especially when the data file is corrupted or missing. Currently, the app may crash or show unclear error messages in such cases.

### LINKED ISSUE #126: No graceful shutdown handling
The application doesn't handle graceful shutdown properly when interrupted or closed unexpectedly. This could lead to data loss or corrupted state files.

### LINKED ISSUE #127: CI pipeline runs on outdated checkout@main instead of v4
The GitHub Actions workflow uses deprecated 'actions/checkout@main' instead of the current stable version 'actions/checkout@v4'. This may cause security warnings and potential build failures in the future.

### LINKED ISSUE #128: Duplicate checkout steps in CI workflow
The CI workflow has two redundant checkout steps (lines 13-14 and 16-19) which may cause conflicts. The first checkout without ref specification and the second with ref=master are redundant.

### LINKED ISSUE #129: Missing ExitCommand in User Guide command summary table
The User Guide command summary table at the end includes all commands except 'exit'. The exit command is documented earlier but missing from the quick reference table, making it inconsistent.

### LINKED ISSUE #130: Help window still points to AddressBook User Guide instead of Tutor Central
The HelpWindow.java still references the old AddressBook User Guide URL (https://se-education.org/addressbook-level3/UserGuide.html) instead of the Tutor Central User Guide. This confuses users when they click for help.

### LINKED ISSUE #131: Day validation accepts any alphanumeric string, not just valid days
The Day.java validation regex '[\\p{Alnum}][\\p{Alnum} ]*' accepts strings like 'xyz123' or 'abc def' as valid days. Should only accept actual day names like 'Monday', 'Tuesday', etc. This allows invalid data entry.

### LINKED ISSUE #132: Time validation accepts any 4-digit number, not valid time format
The Time.java validation regex '[0-9]{4}' accepts any 4-digit number like '9999' or '0000'. Should validate for proper 24-hour time format (0000-2359) to prevent invalid time entries.

### LINKED ISSUE #133: CI workflow uses deprecated checkout@main and has redundant steps
GitHub Actions workflow uses deprecated 'actions/checkout@main' (should be v4) and has duplicate checkout steps that may cause conflicts. This affects CI reliability.

### PR DESCRIPTION
**Pull request by AbhishekParanjape**
# Fix Alpha Bugs And Validation Improvements

## Summary
This PR addresses all 13 alpha bugs identified in the codebase, focusing on complete Tutor Central branding consistency, improved input validation, enhanced error handling, and better test coverage.

## Fixed Issues
- #130: Help window still points to AddressBook User Guide instead of Tutor Central
- #131: Day validation accepts any alphanumeric string, not just valid days  
- #132: Time validation accepts any 4-digit number, not valid time format
- #129: Missing ExitCommand in User Guide command summary table
- #124: Incomplete test coverage in JsonUtilTest
- #120: App still shows 'AddressBook' branding in startup logs
- #121: Data file still uses addressbook.json instead of tutorcentral.json
- #122: JAR file still named addressbook.jar
- #123: Config file references should be updated from AddressBook to Tutor Central
- #126: No graceful shutdown handling
- #125: Missing error handling for file operations

### UI & Documentation
- **HelpWindow**: Updated URL to point to Tutor Central User Guide
- **User Guide**: Added missing Exit command to command summary table
- **Branding**: All AddressBook references updated to Tutor Central in logs and comments

### Input Validation
- **Day Validation**: Fixed regex to accept only valid day names and abbreviations (Mon, Tue, etc.)
- **Time Validation**: Updated regex to enforce proper 24-hour format (0000-2359)
- **Test Coverage**: Implemented missing test methods in JsonUtilTest

### Configuration & Build
- **JAR Output**: Changed filename from `addressbook.jar` to `tutorcentral.jar`
- **Data File**: Default data file changed from `addressbook.json` to `tutorcentral.json`
- **Comments**: Updated storage and logic class documentation

### Error Handling & Reliability
- **File Operations**: Enhanced error handling with user-friendly messages
- **Logging**: Improved error messages for configuration and preference failures
- **Graceful Recovery**: Added fallback behavior for file save failures

## Testing
- All existing tests continue to pass
- New JsonUtilTest methods improve coverage
- Day and Time validation thoroughly tested
- Build and checkstyle validation passes

## Breaking Changes
- Default data file changed from `addressbook.json` to `tutorcentral.json`
- JAR filename changed from `addressbook.jar` to `tutorcentral.jar`

## Migration Notes
Users with existing `addressbook.json` files should rename them to `tutorcentral.json` to maintain data continuity.

## Checklist
- [x] Code follows project style guidelines
- [x] Self-review of the code
- [x] All tests pass
- [x] Build passes
- [x] No new warnings introduced
- [x] Documentation updated
- [x] Breaking changes documented

Closes #121, closes #122, closes #123, closes #124, closes #125, closes #126, closes #127, closes #128, closes #129, closes #130, closes #131, closes #132, closes #133

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Day.java [hunk 1]
```diff
@@ -9,8 +9,10 @@
  */
 public class Day {
     public static final String MESSAGE_CONSTRAINTS =
-            "Days should only contain alphanumeric characters and spaces, and should not be blank";
-    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} ]*";
+            "Days should be valid day names (Monday/Mon, Tuesday/Tue, Wednesday/Wed, "
+            + "Thursday/Thu, Friday/Fri, Saturday/Sat, Sunday/Sun) in any case";
+    public static final String VALIDATION_REGEX = "^(?i)(Monday|Mon|Tuesday|Tue|Wednesday|Wed|Thursday|Thu|"
```
Comment (stinkray77) [inline src/main/java/seedu/address/model/person/Day.java]: The addition of (?i) correctly handles case-insensitivity. However, ensure that the logic in the rest of the class (or where this is used) also handles the mapping of "Mon" to "Monday" if you intend for them to be treated as the same entity.

Also, consider if MESSAGE_CONSTRAINTS should explicitly mention that abbreviations are allowed, to match the regex logic.

File: src/test/java/seedu/address/commons/util/JsonUtilTest.java [hunk 2]
```diff
@@ -39,7 +39,21 @@ public void deserializeObjectFromJsonFile_noExceptionThrown() throws IOException
         assertEquals(serializableTestClass.getMapOfIntegerToString(), SerializableTestClass.getHashMapTestValues());
     }
 
-    //TODO: @Test jsonUtil_readJsonStringToObjectInstance_correctObject()
+    @Test
```
Comment (stinkray77) [inline src/test/java/seedu/address/commons/util/JsonUtilTest.java]: Great job implementing the @TODO tests. It's important to ensure our utility classes are fully verified, especially when we are relying on them for data persistence in Tutor Central.
