### PR TITLE
fix: resolve alpha bugs in input validation and storage

### LINKED ISSUE #144: Day abbreviation bypasses deduplication check
File: [logic/parser/ParserUtil.java](vscode-webview://19u2ca8ddudgvlvfo70id479eq63dm7k244g6hvfc8n9gkivnp3c/src/main/java/seedu/address/logic/parser/ParserUtil.java), parseDays()

Day.equals() compares raw strings, so "Monday" ≠ "Mon" even though they mean the same day. This means:

add n/Alice e/a@b.com a/123 ec/12345678 d/Monday d/Mon ti/1000 ti/1100
Creates a student with two separate "days" for Monday — both pass the size check (2 == 2) and both get stored. The schedule has Monday listed twice.

### LINKED ISSUE #145: Duplicate same-day/time silently collapsed
File: [logic/parser/AddCommandParser.java](vscode-webview://19u2ca8ddudgvlvfo70id479eq63dm7k244g6hvfc8n9gkivnp3c/src/main/java/seedu/address/logic/parser/AddCommandParser.java) lines 74–82

add n/Alice e/a@b.com a/123 ec/12345678 d/Monday d/Monday ti/1000 ti/1000
Both dayList and timeList become Sets of size 1 (HashSet deduplication). The size check passes silently, no error is raised, and the duplicate input is swallowed without any feedback to the user.

### LINKED ISSUE #146: Phone number has no maximum length
File: [model/person/Phone.java](vscode-webview://19u2ca8ddudgvlvfo70id479eq63dm7k244g6hvfc8n9gkivnp3c/src/main/java/seedu/address/model/person/Phone.java) line 13

VALIDATION_REGEX = "\\d{3,}" — allows arbitrarily long numbers. This is accepted:

add n/Alice e/a@b.com a/123 ec/12345678 p/99999999999999999999999999999

### LINKED ISSUE #147: JSON deserialization doesn't validate lesson names
File: [storage/JsonAdaptedPerson.java](vscode-webview://19u2ca8ddudgvlvfo70id479eq63dm7k244g6hvfc8n9gkivnp3c/src/main/java/seedu/address/storage/JsonAdaptedPerson.java) lines 211–215

When loading tutorcentral.json, the status string is validated (AttendanceStatus.isValidStatus) but the lesson name key is not validated at all. Manually editing the JSON with a lesson key like "!!!" or "" loads it into memory and then saves it back without error.

### LINKED ISSUE #149: Name class has copy-paste comment error
File: [model/person/Name.java](vscode-webview://19u2ca8ddudgvlvfo70id479eq63dm7k244g6hvfc8n9gkivnp3c/src/main/java/seedu/address/model/person/Name.java) line ~15

The constraint comment says "The first character of the address must not be a whitespace" — it should say "name". Minor documentation bug.

### PR DESCRIPTION
**Pull request by stinkray77**
## Summary

Fixes #149
Fixes #147 
Fixes #146 
Fixes #145 
Fixes #144 

- **Bug 1 – Day abbreviation bypass**: `d/Mon` and `d/Monday` were treated as different days (different strings, both valid in regex), allowing a student to be scheduled twice on the same day. Fixed by normalizing abbreviations to full names in the `Day` constructor.
- **Bug 2 – Silent day/time duplicate**: `d/Monday d/Monday ti/1000 ti/1000` passed validation because Set deduplication collapsed both to size 1. Fixed by checking raw list sizes before converting to Sets in `AddCommandParser` and `EditCommandParser`.
- **Bug 3 – Phone number length unbounded**: `\\d{3,}` accepted arbitrarily long numbers. Fixed by capping at 15 digits per the ITU-T E.164 standard.
- **Bug 4 – JSON deserialization skips lesson/subject validation**: Attendance records loaded from a manually-edited JSON file could contain invalid subject or lesson name keys without error. Fixed by validating both keys in `JsonAdaptedPerson.toModelType()`.
- **Bug 5 – Copy-paste comment error**: `Name.java` said "The first character of the **address**…" — fixed to say "name".

## Test plan
- [x] `./gradlew test` passes
- [x] `./gradlew checkstyleMain checkstyleTest` passes

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -11,8 +11,8 @@ public class Phone {
 
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Phone numbers should only contain numbers, and it should be at least 3 digits long";
-    public static final String VALIDATION_REGEX = "\\d{3,}";
+            "Phone numbers should only contain numbers, and it should be between 3 and 15 digits long";
```
Comment (AbhishekParanjape) [inline src/main/java/seedu/address/model/person/Phone.java]: Good find that phone numbers have a upper limit!

**Review by bombyz003 — COMMENTED** [review]
LGTM! code was made a bit lengthier but has positive effects.
