### PR TITLE
Fix `remark` command bug

### LINKED ISSUE #172: `remark INDEX` without `r/` prefix silently removes the student's remark
Omitting the `r/` prefix in `remark` still clears the remark instead of rejecting the command.

Steps to reproduce:
  1. Add a remark to a student, e.g. `remark 1 r/Needs extra help`.
  2. Run `remark 1` without the `r/` prefix.

Expected:
  - The command is rejected as invalid because the documented format is `remark INDEX r/REMARK`.

Actual:
  - The student's remark is removed.

Notes/Evidence:
  - `RemarkCommandParser` uses `argMultimap.getValue(PREFIX_REMARK).orElse("")`, so missing `r/` is treated as an empty remark.
  - This is risky because a mistyped command can silently delete user-entered notes.

### PR DESCRIPTION
**Pull request by daynerss1**
Omitting the r/ prefix in remark clears the remark. In order to ensure consistency with other commands, omitting prefixes should not be allowed.

Task:
- Made `r/` prefix compulsory in a `remark` command.
- To clear a remark from a student, use `r/` (empty space behind)

Fixes #172

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/RemarkCommandParser.java [hunk 1]
```diff
@@ -22,18 +21,23 @@ public class RemarkCommandParser implements Parser<RemarkCommand> {
...
             index = ParserUtil.parseIndex(argMultimap.getPreamble());
-        } catch (IllegalValueException ive) {
+        } catch (ParseException pe) {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
-                    RemarkCommand.MESSAGE_USAGE), ive);
+                    RemarkCommand.MESSAGE_USAGE), pe);
         }
 
-        String remark = argMultimap.getValue(PREFIX_REMARK).orElse("");
+        if (argMultimap.getValue(PREFIX_REMARK).isEmpty()) {
```
Comment (stinkray77) [inline src/main/java/seedu/address/logic/parser/RemarkCommandParser.java]: This explicit check for the presence of the r/ prefix is necessary because the remark command requires a remark (even an empty one). By throwing a ParseException here, you provide a much better user experience than letting it fail later with a generic error.
